language: node_js
sudo: false
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nikita' ]; then cd .. && eval "mv $currentfolder generator-nikita" && cd generator-nikita; fi
before_deploy:
  - npm install json
  - node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
matrix:
  include:
    - node_js: '6.11.1'
      env: CXX=g++-4.8
    - node_js: '7.10.1'
      env: CXX=g++-4.8
    - node_js: '10.13.0'
      env: CXX=g++-4.8
    - node_js: '8.1.4'
      env:
        - TEMPLATE=web-app
        - CXX=g++-4.8
    - node_js: '8.1.4'
      env:
        - TEMPLATE=symfony
        - CXX=g++-4.8
    - node_js: '8.1.4'
      env:
        - TEMPLATE=wordpress
        - CXX=g++-4.8
    - node_js: '8.1.4'
      env:
        - TEMPLATE=spring-boot
        - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: "K9xT+9vCOnD4cEXRTogF7AX1LPjT32os9193ghUEQMdgPIn8GKE1YXqWjlGDUJCzPT1XrTqoZUkbmebK+BBI+hH3AmVtHhK4z27vmrss98SrCx0Yog+RxUqPWA2VAaAt+w3SIeJrl8Z3fDBQaolii5fFx8Rn8HgtVIQnCffNhBY="
  on:
    tags: true
    repo: nikita-kit/generator-nikita
    all_branches: true
    node: 4.8.4
